backend:
  name: git-gateway
  branch: main # or "master" if that’s your default branch

media_folder: "images" # Directly use your 'images' folder in the root directory
public_folder: "/images" # Same as the folder above

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts" # Your posts folder in the root directory
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
