backend:
  name: git-gateway
  branch: main # or "master" if that’s your default branch

media_folder: "/images" # Folder for images (adjust to your template)
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "/_posts" # Change to the folder containing your posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
